[project]
name = "aptitude-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "amqp==5.3.1",
    "asgiref==3.8.1",
    "azure-storage-blob>=12.28.0",
    "bcrypt==4.2.0",
    "beautifulsoup4==4.12.3",
    "billiard==4.2.1",
    "celery==5.4.0",
    "certifi==2024.8.30",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "colorama==0.4.6",
    "confluent-kafka>=2.14.0",
    "decorator==4.4.2",
    "diff-match-patch==20241021",
    "Django==4.2.16",
    "django-celery-results>=2.6.0",
    "django-cors-headers==4.4.0",
    "django-environ==0.11.2",
    "django-filter==24.3",
    "django-import-export==4.1.1",
    "django-multiselectfield==0.1.13",
    "django-silk>=5.5.0",
    "django-storages>=1.14.6",
    "djangorestframework==3.15.2",
    "djangorestframework-simplejwt==5.3.1",
    "dnspython==2.6.1",
    "drf-yasg==1.21.7",
    "et_xmlfile==1.1.0",
    "idna==3.10",
    "imageio==2.35.1",
    "imageio-ffmpeg==0.5.1",
    "inflection==0.5.1",
    "kombu==5.4.2",
    "moviepy==1.0.3",
    "mysql-connector-python==9.1.0",
    "mysqlclient>=2.2.8",
    "numpy==1.26.4",
    "openpyxl==3.1.5",
    "packaging==24.1",
    "pandas==2.2.3",
    "pdfkit==1.0.0",
    "pillow==10.4.0",
    "proglog==0.1.10",
    "prompt_toolkit==3.0.48",
    "PyJWT==2.9.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "PyYAML==6.0.2",
    "random2==1.0.2",
    "requests==2.32.3",
    "six==1.16.0",
    "SkPy==0.11",
    "soupsieve==2.6",
    "sqlparse==0.5.1",
    "tablib==3.5.0",
    "tqdm==4.66.5",
    "typing_extensions==4.12.2",
    "tzdata==2024.2",
    "uritemplate==4.1.1",
    "urllib3==2.2.3",
    "vine==5.1.0",
    "wcwidth==0.2.13",
    "XlsxWriter==3.2.0",
]
