from .designation import Designation
from .custom_user import CustomUser
from .allowed_content_type import AllowedContentType
from .crm_users import Users
from .crm_employee_details import EmployeeDetails
from .crm_designations import Designations
from .zkteco_personnel_employee import PersonnelEmployee
from .zkteco_iclock_transaction import IclockTransaction
from .crm_leaves import Leaves
from .crm_leave_types import LeaveTypes
from .crm_holidays import Holidays
