from django.db import models


class PersonnelEmployee(models.Model):
    create_time = models.DateTimeField(blank=True, null=True)
    create_user = models.CharField(max_length=150, blank=True, null=True)
    change_time = models.DateTimeField(blank=True, null=True)
    change_user = models.CharField(max_length=150, blank=True, null=True)
    status = models.SmallIntegerField()
    id = models.CharField(primary_key=True, max_length=36)
    emp_code = models.CharField(max_length=20)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=25, blank=True, null=True)
    nickname = models.CharField(max_length=100, blank=True, null=True)
    passport = models.CharField(max_length=30, blank=True, null=True)
    driver_license_automobile = models.CharField(max_length=30, blank=True, null=True)
    driver_license_motorcycle = models.CharField(max_length=30, blank=True, null=True)
    enable_outdoor_management = models.SmallIntegerField(blank=True, null=True)
    photo = models.CharField(max_length=200, blank=True, null=True)
    self_password = models.CharField(max_length=128, blank=True, null=True)
    device_password = models.CharField(max_length=20, blank=True, null=True)
    dev_privilege = models.IntegerField(blank=True, null=True)
    card_no = models.CharField(max_length=20, blank=True, null=True)
    acc_group = models.CharField(max_length=5, blank=True, null=True)
    acc_timezone = models.CharField(max_length=20, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    postcode = models.CharField(max_length=10, blank=True, null=True)
    office_tel = models.CharField(max_length=20, blank=True, null=True)
    contact_tel = models.CharField(max_length=20, blank=True, null=True)
    mobile = models.CharField(max_length=20, blank=True, null=True)
    national = models.CharField(max_length=50, blank=True, null=True)
    religion = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=20, blank=True, null=True)
    enroll_sn = models.CharField(max_length=20, blank=True, null=True)
    ssn = models.CharField(max_length=20, blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)
    hire_date = models.DateField(blank=True, null=True)
    verify_mode = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    is_admin = models.IntegerField()
    emp_type = models.IntegerField(blank=True, null=True)
    enable_att = models.IntegerField()
    enable_payroll = models.IntegerField()
    enable_overtime = models.IntegerField()
    enable_holiday = models.IntegerField()
    enable_whatsapp = models.IntegerField()
    whatsapp_exception = models.IntegerField()
    whatsapp_punch = models.IntegerField()
    deleted = models.IntegerField()
    reserved = models.IntegerField(blank=True, null=True)
    del_tag = models.IntegerField(blank=True, null=True)
    app_status = models.SmallIntegerField(blank=True, null=True)
    app_role = models.SmallIntegerField(blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    enable_sms = models.IntegerField()
    sms_exception = models.IntegerField()
    sms_punch = models.IntegerField()
    last_login = models.DateTimeField(blank=True, null=True)
    is_active = models.IntegerField()
    # department = models.ForeignKey('PersonnelDepartment', models.DO_NOTHING, blank=True, null=True)
    # location = models.ForeignKey('PersonnelLocation', models.DO_NOTHING, blank=True, null=True)
    # position = models.ForeignKey('PersonnelPosition', models.DO_NOTHING, blank=True, null=True)
    # company = models.ForeignKey('PersonnelCompany', models.DO_NOTHING, blank=True, null=True)
    otp = models.CharField(max_length=8, blank=True, null=True)
    verified_employee = models.IntegerField(blank=True, null=True)
    app_punch_status = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'personnel_employee'
        # unique_together = (('emp_code', ),)
